repos:
  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/PyCQA/flake8
    rev: main
    hooks:
      - id: flake8
        args: [--config=.flake8, --ignore=E203]

  - repo: https://github.com/pycqa/isort
    rev: main
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: main
    hooks:
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
